---
- name: Remove worker nodes
  hosts: kube_node
  become: true
  become_user: root
  roles:
    - role: kubeadm/remove-node
  serial: 1

- name: Remove control-plane nodes
  hosts: kube_control_plane,!kube_control_plane[0]
  become: true
  become_user: root
  roles:
    - role: kubeadm/remove-node
  serial: 1

- name: Remove initial control-plane node
  hosts: kube_control_plane[0]
  become: true
  become_user: root
  roles:
    - role: kubeadm/remove-node
  serial: 1
