---
- name: Unhold kubeadm
  ansible.builtin.shell: apt-mark unhold kubeadm
  changed_when: false

- name: Upgrade kubeadm
  ansible.builtin.apt:
    name: ["kubeadm={{ k8s_component_version }}-*"]
    update_cache: true

- name: Hold kubeadm
  ansible.builtin.shell: apt-mark hold kubeadm
  changed_when: false

- name: Get kubeadm version
  ansible.builtin.shell: kubeadm version
  register: kubeadm_version
  changed_when: false

- name: Show kubeadm version
  ansible.builtin.debug:
    msg: "{{ kubeadm_version.stdout_lines }}"
