---
name: Ansible Lint and YAML Lint

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches: [main]

jobs:
  lint-ansible:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==11.8.0 ansible-lint

      - name: Run ansible-lint
        run: ansible-lint ./playbooks

  lint-yaml:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==11.8.0 yamllint

      - name: Run yamllint
        run: yamllint .
